### ISSUE TITLE
Please fall back to probe_read() if kernels doesn't support probe_read_{user,kernel}

### ISSUE THREAD

**Issue by nitanmarcel** [Mufanc/z-loader#3]
Unless arya handles this already the code should fall back to probe_read instead of the kernel, user counterpart to ensure compatibility with older kernels than 5.5 (I think)

On most kernels, a kernel side patch will also be required to be able to read user pointers correctly

https://github.com/nitanmarcel/android_kernel_oneplus_sdm845-bpf/commit/7dcf378f5f14072cfce26ceeb4ef3cf568623c0b

**Comment by nitanmarcel** [comment]
Actually this seems to use some features only available on 5.8.

I would suggest a port to libbpf which has fallbacks for lower kernel versions

**Comment by Mufanc** [comment]
First and foremost, thank you very much for your suggestion! This is just a very basic demonstration project aimed at proposing a method for on-demand injection into the Zygote process. Due to my busy work schedule, I have limited time to dedicate to this project, so the code implementation has many imperfections and errors. I welcome the community to build more refined and practical applications based on this idea.
